Remove AltTester and add it as a submodule
alttester/EXAMPLES-NewInputSystem--CoinCollector-CSharp pull request #4
Opened 2022-11-16 09:00 UTC by andreion1ca

AltTester was removed and added as a submodule to make it easier in the future to update the example

2022-12-06 07:28 UTC, andreion1ca commented
@RobertPoienar @robert-altom @ReichEdvin @gomboskriszta15 @iulianatodoran can one of you have a look at this PR?

2022-12-06 08:24 UTC, RobertPoienar approved these changes
LGTM

2022-12-06 08:48 UTC, iulianatodoran commented
- As discussed earlier this month, it would be helpful to document in a `README.md` file the steps if we use a submodule, so the users have clear info on what to do to get the AltTester submodule in the project. 
- Also, there was an idea to provide a link for users to download the AltTester package with instructions for importing if they prefer this method, and not to use the submodule. 

So, **in conclusion**, the` README.md` file should contain both ways of using AltTester in the project
- add the submodule and use the master branch
- link for download AltTester + import in Unity

2022-12-06 11:41 UTC, iulianatodoran commented on README.md
> +    - in the <i> New Input System proj/Assets </i> folder add the submodule using the <i><b> git submodule add https://github.com/alttester/AltTester-Unity-SDK.git </b></i> command;
For commands, you could use  ``  at the beginning and the end of the command too look like this: ``command``.

2022-12-06 11:43 UTC, iulianatodoran commented on README.md
> +    - open the project in Unity and from the menu, go to <i> Assets -> Import Packages -> Custom Package... </i> and select the AltTester Unity Package downloaded before;
easier way is to drag-n-drop directly in the Assets folder

2022-12-06 11:47 UTC, iulianatodoran commented on README.md
> +    - make sure that the submodule added is on the master branch (you can use the following command <i><b> cd AltTester-Unity-SDK && git checkout master</b></i>).
When a release is made for AltTester the user has to make a git pull on the master branch, maybe this info is useful too if they already have the project and thus are aware that the AltTester version was upgraded

2022-12-14 07:36 UTC, RobertPoienar requested changes
.gitmodules shouldn't be empty, it seems you didn't added correctly the submodule

2022-12-14 07:58 UTC, iulianatodoran commented on README.md
> +    - a pop-up will appear, select All and click on Import.
this step seems a bit too much information to give, the users in unity usually know how to import packages so the previous step should be enough.

2022-12-20 09:51 UTC, merged